// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseContainer: typeof import('I:/PROJECTS SITES/projects/weather-app-vitesse/src/components/base/BaseContainer.vue')['default']
    BaseSpinner: typeof import('I:/PROJECTS SITES/projects/weather-app-vitesse/src/components/base/BaseSpinner.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    DuringDay: typeof import('I:/PROJECTS SITES/projects/weather-app-vitesse/src/components/DuringDay.vue')['default']
    Footer: typeof import('I:/PROJECTS SITES/projects/weather-app-vitesse/src/components/Footer.vue')['default']
    ForecastCard: typeof import('I:/PROJECTS SITES/projects/weather-app-vitesse/src/components/ForecastCard.vue')['default']
    Header: typeof import('I:/PROJECTS SITES/projects/weather-app-vitesse/src/components/Header.vue')['default']
    IndexForecastCard: typeof import('I:/PROJECTS SITES/projects/weather-app-vitesse/src/components/IndexForecastCard.vue')['default']
    README: typeof import('I:/PROJECTS SITES/projects/weather-app-vitesse/src/components/README.md')['default']
  }
}

export { }
